version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: nestjs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: social_network
    ports:
      - '5432:5432'